<?php

declare(strict_types=1);

namespace Whity\Core\i18n;

use FilesystemIterator;
use JsonException;
use RuntimeException;

/**
 * The committed English catalogue: `database/i18n/<domain>.json`.
 *
 * WHY A COMMITTED FILE AT ALL, when the catalogue is derived from code?
 * ---------------------------------------------------------------------
 *  1. THE BACKEND CANNOT SEE THE FRONTEND. `.dockerignore` keeps `web/` out of
 *     the release image, and rightly so — the backend serves no TSX. But the
 *     command that seeds the strings runs INSIDE that image. `database/` ships,
 *     so this is the vehicle that carries the strings across.
 *  2. IT MAKES THE STRINGS REVIEWABLE. "What English text did this PR add or
 *     change?" is one file diff rather than a re-read of every screen.
 *  3. IT GIVES CI SOMETHING TO COMPARE. The drift gate regenerates and diffs,
 *     the same shape as the OpenAPI spec check — a check with no database and
 *     no network.
 *
 * ONE FILE PER DOMAIN, NOT ONE BIG FILE. This is the property that lets the
 * extraction fan out: two agents converting two areas write two different
 * files and never conflict. A single catalogue would put every one of them in
 * the same merge.
 *
 * THE CATALOGUE MIRRORS CODE; THE DATABASE ACCUMULATES. A key that leaves the
 * source leaves this file on the next regeneration — CI insists on it. The
 * database is the opposite: {@see TranslationSync} only ever inserts, because
 * rows there carry human work (an edited English string, a finished Arabic
 * translation) that no scanner may destroy.
 */
final class TranslationCatalog
{
    /**
     * The language the catalogue is written in — the same constant the runtime
     * fallback chain uses, so the seeding route and the read path can never
     * disagree about which language is the source.
     */
    public const SOURCE_LANGUAGE = LanguageRegistry::SOURCE_LANGUAGE;

    /** Where the catalogue lives, relative to the repository root. */
    public const DIRECTORY = 'database/i18n';

    /**
     * A plugin domain (`acme:catalog`) cannot be a filename on Windows, so the
     * namespace separator is encoded on the way to disk. Core domains are bare
     * and unaffected.
     *
     * `-` and not `_`: a domain slug is `[a-z][a-z0-9_]*`, so `acme__catalog`
     * is itself a VALID bare domain — encoding with `__` would map it and
     * `acme:catalog` to the same file, and one of the two would silently
     * overwrite the other's strings on every regeneration. A hyphen cannot
     * occur in a slug, so the mapping is one-to-one in both directions.
     */
    private const NAMESPACE_FILE_SEPARATOR = '-';

    private const HEADER_NOTICE = 'Generated by `whity-cli i18n:extract` from the t() calls in the source. '
        . 'Do not edit by hand: edit the English text at the call site and regenerate. '
        . 'Seed it into the database with `whity-cli i18n:sync`.';

    public function __construct(
        private readonly string $baseDir,
    ) {
    }

    public function directory(): string
    {
        return $this->baseDir . '/' . self::DIRECTORY;
    }

    /**
     * The catalogue as committed, grouped by domain and sorted.
     *
     * @return array<string, array<string, string>>
     */
    public function read(): array
    {
        $directory = $this->directory();
        if (!is_dir($directory)) {
            return [];
        }

        $catalog = [];
        foreach (new FilesystemIterator($directory, FilesystemIterator::SKIP_DOTS) as $file) {
            $path = (string) $file;
            if (!is_file($path) || !str_ends_with($path, '.json')) {
                continue;
            }

            $contents = file_get_contents($path);
            if ($contents === false) {
                throw new RuntimeException("Unreadable catalogue file: {$path}");
            }

            try {
                /** @var array<string, mixed> $decoded */
                $decoded = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
            } catch (JsonException $e) {
                throw new RuntimeException("Malformed catalogue file {$path}: " . $e->getMessage(), 0, $e);
            }

            $domain = is_string($decoded['domain'] ?? null)
                ? $decoded['domain']
                : self::domainFromFileName(basename($path));
            $keys = is_array($decoded['keys'] ?? null) ? $decoded['keys'] : [];

            $strings = [];
            foreach ($keys as $key => $text) {
                if (is_string($key) && is_string($text)) {
                    $strings[$key] = $text;
                }
            }
            ksort($strings);
            $catalog[$domain] = $strings;
        }

        ksort($catalog);

        return $catalog;
    }

    /**
     * Write the catalogue, one file per domain, and delete the files of domains
     * that no longer exist in code.
     *
     * @param array<string, array<string, string>> $catalog
     * @return array{written: list<string>, unchanged: list<string>, deleted: list<string>}
     */
    public function write(array $catalog): array
    {
        $directory = $this->directory();
        if (!is_dir($directory) && !mkdir($directory, 0o775, true) && !is_dir($directory)) {
            throw new RuntimeException("Could not create catalogue directory: {$directory}");
        }

        $written = [];
        $unchanged = [];
        $expected = [];

        ksort($catalog);
        foreach ($catalog as $domain => $keys) {
            $fileName = self::fileNameFor($domain);
            $expected[$fileName] = true;
            $path = $directory . '/' . $fileName;
            $rendered = self::render($domain, $keys);

            $current = is_file($path) ? file_get_contents($path) : false;
            if ($current !== false && self::normalise($current) === $rendered) {
                $unchanged[] = $fileName;
                continue;
            }

            if (file_put_contents($path, $rendered) === false) {
                throw new RuntimeException("Could not write catalogue file: {$path}");
            }
            $written[] = $fileName;
        }

        $deleted = [];
        foreach (new FilesystemIterator($directory, FilesystemIterator::SKIP_DOTS) as $file) {
            $path = (string) $file;
            $name = basename($path);
            if (!is_file($path) || !str_ends_with($name, '.json') || isset($expected[$name])) {
                continue;
            }
            unlink($path);
            $deleted[] = $name;
        }

        sort($deleted);

        return ['written' => $written, 'unchanged' => $unchanged, 'deleted' => $deleted];
    }

    /**
     * The exact bytes a domain's catalogue file must contain.
     *
     * Sorted and pretty-printed so a new string shows up as one added line, and
     * unescaped so a reviewer reads the sentence rather than `é`.
     *
     * @param array<string, string> $keys
     */
    public static function render(string $domain, array $keys): string
    {
        ksort($keys);

        $payload = [
            'domain' => $domain,
            'notice' => self::HEADER_NOTICE,
            'keys' => $keys === [] ? new \stdClass() : $keys,
        ];

        $json = json_encode(
            $payload,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR
        );

        return $json . "\n";
    }

    /** The catalogue file a domain is stored in. */
    public static function fileNameFor(string $domain): string
    {
        return str_replace(
            TranslationDomain::NAMESPACE_SEPARATOR,
            self::NAMESPACE_FILE_SEPARATOR,
            $domain
        ) . '.json';
    }

    /** The domain a catalogue file holds, inferred from its name. */
    public static function domainFromFileName(string $fileName): string
    {
        return str_replace(
            self::NAMESPACE_FILE_SEPARATOR,
            TranslationDomain::NAMESPACE_SEPARATOR,
            (string) preg_replace('/\.json$/', '', $fileName)
        );
    }

    /**
     * Compare a freshly extracted catalogue against what is committed.
     *
     * @param array<string, array<string, string>> $extracted
     * @param array<string, array<string, string>> $committed
     * @return list<array{domain: string, key: string, kind: string, detail: string}>
     */
    public static function diff(array $extracted, array $committed): array
    {
        $differences = [];

        foreach ($extracted as $domain => $keys) {
            foreach ($keys as $key => $text) {
                if (!array_key_exists($key, $committed[$domain] ?? [])) {
                    $differences[] = [
                        'domain' => $domain,
                        'key' => $key,
                        'kind' => 'missing-from-catalogue',
                        'detail' => $text,
                    ];
                    continue;
                }
                if ($committed[$domain][$key] !== $text) {
                    $differences[] = [
                        'domain' => $domain,
                        'key' => $key,
                        'kind' => 'text-changed',
                        'detail' => 'catalogue says ' . json_encode($committed[$domain][$key], JSON_UNESCAPED_UNICODE)
                            . ', source says ' . json_encode($text, JSON_UNESCAPED_UNICODE),
                    ];
                }
            }
        }

        foreach ($committed as $domain => $keys) {
            foreach ($keys as $key => $text) {
                if (!array_key_exists($key, $extracted[$domain] ?? [])) {
                    $differences[] = [
                        'domain' => $domain,
                        'key' => $key,
                        'kind' => 'absent-from-source',
                        'detail' => $text,
                    ];
                }
            }
        }

        usort($differences, static function (array $a, array $b): int {
            return [$a['domain'], $a['key']] <=> [$b['domain'], $b['key']];
        });

        return $differences;
    }

    /** Line endings a Windows checkout may have introduced are not drift. */
    private static function normalise(string $contents): string
    {
        return str_replace("\r\n", "\n", $contents);
    }
}
